version: "3"

services:
  golang-boilerplate:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: golang-boilerplate:v1
    container_name: golang-boilerplate
    environment:
      - SERVICE_NAME=boilerplate
      - SERVICE_ENV=dev

      - HTTPS_PORT=8000

      - LOG_LEVEL=INFO
      - LOG_PATH=logs/app.log

      - REDIS_ADDRS=172.17.0.1:6379
      - REDIS_PASSWORD=
      - REDIS_CHANNEL=
      - REDIS_DB=
      - REDIS_POOL_SIZE=20

      - KAFKA_BROKERS=172.17.0.1:9092
      - KAFKA_GROUP_ID=boilerplate
      - KAFKA_POOL_SIZE=30
      - KAFKA_SIGNUP_USER_TOPIC=register

      - STATSD_ADDR=172.17.0.1:8125
      - STATSD_PREFIX=boilerplate_prefix
      - STATSD_FLUSH_PERIOD=100

    ports:
      - 8001:8000
    logging:
      driver: fluentd
      options:
        tag: docker
