version: "3"

services:
  kafka-kraft:
    image: bitnami/kafka:3.7
    container_name: kafka-kraft
    restart: always
    ports:
      - "9092:9092"
    environment:
      # configuration is written to: /opt/bitnami/kafka/config/kraft/server.properties
      ALLOW_PLAINTEXT_LISTENER: yes
      # KRaft settings
      KAFKA_CFG_NODE_ID: 0
      KAFKA_CFG_PROCESS_ROLES: controller,broker
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 0@kafka-kraft:9093
      # Listener
      KAFKA_CFG_LISTENERS: BROKER://:9092,CONTROLLER://:9093
      KAFKA_CFG_ADVERTISED_LISTENERS: BROKER://172.17.0.1:9092
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: BROKER:SASL_PLAINTEXT,CONTROLLER:SASL_PLAINTEXT

      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: BROKER
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER

      KAFKA_CFG_SASL_ENABLED_MECHANISMS: PLAIN
      KAFKA_CFG_SASL_MECHANISM_CONTROLLER_PROTOCOL: PLAIN
      KAFKA_CFG_SASL_MECHANISM_INTER_BROKER_PROTOCOL: PLAIN

      KAFKA_CONTROLLER_USER: controller_user
      KAFKA_CONTROLLER_PASSWORD: controller_password

      KAFKA_INTER_BROKER_USER: broker_user
      KAFKA_INTER_BROKER_PASSWORD: broker_password
      # config
      KAFKF_CFG_LOG_RETENTION_HOURS: 168 # 7 days
      KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE: true
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
