all:
  hosts:
    node-db-01:
      ansible_host: 192.168.56.111
      node_ip: 192.168.56.111
      node_name: node-db-01
      pgpool_node_id: 0
    node-db-02:
      ansible_host: 192.168.56.112
      node_ip: 192.168.56.112
      node_name: node-db-02
      pgpool_node_id: 1
    node-db-03:
      ansible_host: 192.168.56.113
      node_ip: 192.168.56.113
      node_name: node-db-03
      pgpool_node_id: 2
  vars:
    # tell every SSH connection in this play to skip host‑key checking
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
    ansible_user: vagrant
