- name: Config failover
  template:
    src: pgpool2/failover.sh.j2
    dest: '{{ pgpool_config_dir }}/failover.sh'
    mode: '0644'
    owner: postgres
    group: postgres

- name: Config follow_primary
  template:
    src: pgpool2/follow_primary.sh.j2
    dest: '{{ pgpool_config_dir }}/follow_primary.sh'
    mode: '0644'
    owner: postgres
    group: postgres

- name: Config recovery
  template:
    src: pgpool2/recovery_1st_stage.j2
    dest: '{{ pg_data_dir }}/recovery_1st_stage'
    mode: '0640'
    owner: postgres
    group: postgres

- name: Config pgpool_remote_start
  template:
    src: pgpool2/pgpool_remote_start.j2
    dest: '{{ pg_data_dir }}/pgpool_remote_start'
    mode: '0640'
    owner: postgres
    group: postgres

- block:
    - name: Copy create_pgpool_recovery script
      template:
        src: pgpool2/create_pgpool_recovery.sh.j2
        dest: '{{ pg_data_dir }}/create_pgpool_recovery.sh'
        mode: '0740'
        owner: postgres
        group: postgres

    - name: Execute the script create_pgpool_recovery.sh
      shell: |
        bash create_pgpool_recovery.sh
      args:
        chdir: '{{ pg_data_dir }}'
      register: result

    - name: Show running script result
      debug:
        var: result

    - name: Remove running config_psql_user script
      file:
        path: '{{ pg_data_dir }}/create_pgpool_recovery.sh'
        state: absent
  when: inventory_hostname == 'node-db-01'

- block: # Client authentication Configuration
    - name: Copy pgool_hba.conf to '{{ pgpool_config_dir }}/pool_hba.conf'
      template:
        src:  pgpool2/pool_hba.conf.j2
        dest: '{{ pgpool_config_dir }}/pool_hba.conf'
        mode: '0644'
        owner: root
        group: root

    - name: Create .pgpoolkey
      template:
        src:  pgpool2/.pgpoolkey.j2
        dest: '{{ postgres_home_dir }}/.pgpoolkey'
        mode: '0600'
        owner: postgres
        group: postgres

    - name: Update pool_passwd with pgpool user
      shell: |
        sudo pg_enc -m -k {{ postgres_home_dir }}/.pgpoolkey -u pgpool {{ pgpool_user_pass }}

    - name: Update pool_passwd with postgres user
      shell: |
        sudo pg_enc -m -k {{ postgres_home_dir }}/.pgpoolkey -u postgres {{ pgpool_user_pass }}

- block: # Watch dog
  - name: Copy escalation.sh
    template:
      src:  pgpool2/escalation.sh.j2
      dest: '{{ pgpool_config_dir }}/escaltion.sh'
      mode: '0600'
      owner: postgres
      group: postgres

- name: Config Pgpool
  template:
    src: pgpool2/pgpool.conf.j2
    dest: '{{ pgpool_config_dir }}/pgpool.conf'
    mode: '0640'
    owner: root
    group: postgres
