#SPDX-License-Identifier: MIT-0
---
# tasks file for roles/postgresql-ha-pgpool2

- block:
    - name: Install PostgreSQL
      include_tasks: install/install_postgresql_debian.yml
      when: ansible_os_family == "Debian"

    - name: Install PostgreSQL
      include_tasks: install/install_postgresql_redhat.yml
      when: ansible_os_family == "RedHat"
  tags: [ install_postgresql, rc_all ]

- block:
    - name: Install Pgpool2
      include_tasks: install/install_pgpool2_debian.yml
      when: ansible_os_family == "Debian"

    - name: Install Pgpool2
      include_tasks: install/install_pgpool2_redhat.yml
      when: ansible_os_family == "RedHat"
  tags: [ install_pgpool2, rc_all ]

- block:
    - name: Init PostgreSQL
      include_tasks: psql/init_psql.yml
      when: ansible_os_family == "RedHat" and inventory_hostname == "node-db-01"
  tags: [ init_psql, rc_all ]

- block:
    - name: Config ssh between servers
      include_tasks: ssh/setup_ssh.yml
  tags: [ config_ssh, rc_all ]

- block:
    - name: Config PostgreSQL 
      include_tasks: psql/config_psql.yml
  tags: [ config_psql, rc_all ]

- block:
    - name: Config pgpool
      include_tasks: pgpool2/config_pgpool.yml
  tags: [ config_pgpool, rc_all ]

# - block:
#     - name: Recover standby nodes
#       include_tasks: recover_standby.yml
#   when: inventory_hostname == "node-db-01"
#   tags: [ recover_standby, rc_all ]
