version: "3"

services:
  postgresql:
    image: postgres:16-alpine
    restart: always
    container_name: postgres16
    environment:
      - POSTGRES_PASSWORD=changeme
      - POSTGRESQL_SHARED_PRELOAD_LIBRARIES=pg_stat_statements
    ports:
      - 5434:5432
    volumes:
      - postgresql16_data:/var/lib/postgresql/data

volumes:
  postgresql16_data:
    name: postgresql16_data
    driver: local
