{
 "title": "Pgpool-II-Influxdb",
 "tags": [ "pgpool" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "backend_nodes",
    "query": {
     "query": "SHOW TAG VALUES FROM \"pgpool2_pool_nodes_status\" WITH KEY = \"hostname\""
    }
   }
  ]
 },
 "panels": [
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Backend Status",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "hostname::tag" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pgpool2_pool_nodes_status",
     "query": "SELECT \"gauge\" FROM \"pgpool2_pool_node_stat\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Active Connections Ratio",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pgpool2_frontend_used_ratio",
     "query": "SELECT last(\"gauge\") FROM \"pgpool2_frontend_used_ratio\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Active Connectios",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 11, "y": 1 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pgpool2_frontend_used",
     "query": "SELECT mean(\"gauge\") FROM \"pgpool2_frontend_used\" WHERE $timeFilter GROUP BY time($__interval), \"hostname\" fill(null)",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pgpool2_frontend_total",
     "query": "SELECT mean(\"gauge\") FROM \"pgpool2_frontend_total\" WHERE $timeFilter GROUP BY time($__interval), \"hostname\" fill(null)",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Replication delay",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "hostname::tag" ], "type": "tag" },
      { "params": [ "role::tag" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pgpool2_pool_nodes_replication_delay",
     "query": "SELECT mean(\"gauge\") FROM \"pgpool2_pool_nodes_replication_delay\" WHERE $timeFilter AND \"hostname\" =~ /$backend_nodes/ GROUP BY time($__interval), \"hostname\", \"role\" fill(null)",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Error Message Counts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Error Message Counts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 8 },
   "targets": [
    {
     "query": "SELECT non_negative_derivative(mean(\"counter\"),1s) FROM \"pgpool2_pool_backend_stats_error_cnt\" WHERE $timeFilter AND \"hostname\" =~ /$backend_nodes/ GROUP BY time($__interval), \"hostname\", \"role\" fill(null)"
    }
   ]
  },
  {
   "title": "Fatal Message Counts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 8 },
   "targets": [
    {
     "query": "SELECT non_negative_derivative(mean(\"counter\"),1s) FROM \"pgpool2_pool_backend_stats_fatal_cnt\" WHERE $timeFilter AND \"hostname\" =~ /$backend_nodes/ GROUP BY time($__interval), \"hostname\", \"role\" fill(null)"
    }
   ]
  },
  {
   "title": "Panic Message Counts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 14, "y": 8 },
   "targets": [
    {
     "query": "SELECT non_negative_derivative(mean(\"counter\"),1s) FROM \"pgpool2_pool_backend_stats_panic_cnt\" WHERE $timeFilter AND \"hostname\" =~ /$backend_nodes/ GROUP BY time($__interval), \"hostname\", \"role\" fill(null)"
    }
   ]
  },
  { "title": "SQL Command Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "SELECT statement counts",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 17 },
   "targets": [
    {
     "query": "SELECT non_negative_derivative(mean(\"counter\"),1s) FROM \"pgpool2_pool_backend_stats_select_cnt\" WHERE $timeFilter AND \"hostname\" =~ /$backend_nodes/ GROUP BY time($__interval), \"hostname\", \"role\" fill(null)"
    }
   ]
  },
  {
   "title": "DELETE statement counts",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 7, "y": 17 },
   "targets": [
    {
     "query": "SELECT non_negative_derivative(mean(\"counter\"),1s) FROM \"pgpool2_pool_backend_stats_delete_cnt\" WHERE $timeFilter AND \"hostname\" =~ /$backend_nodes/ GROUP BY time($__interval), \"hostname\", \"role\" fill(null)"
    }
   ]
  },
  {
   "title": "INSERT statement counts",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 14, "y": 17 },
   "targets": [
    {
     "query": "SELECT non_negative_derivative(mean(\"counter\"),1s) FROM \"pgpool2_pool_backend_stats_insert_cnt\" WHERE $timeFilter AND \"hostname\" =~ /$backend_nodes/ GROUP BY time($__interval), \"hostname\", \"role\" fill(null)"
    }
   ]
  },
  {
   "title": "UPDATE statement counts",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 23 },
   "targets": [
    {
     "query": "SELECT non_negative_derivative(mean(\"counter\"),1s) FROM \"pgpool2_pool_backend_stats_update_cnt\" WHERE $timeFilter AND \"hostname\" =~ /$backend_nodes/ GROUP BY time($__interval), \"hostname\", \"role\" fill(null)"
    }
   ]
  },
  {
   "title": "DDL statement counts",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 7, "y": 23 },
   "targets": [
    {
     "query": "SELECT non_negative_derivative(mean(\"counter\"),1s) FROM \"pgpool2_pool_backend_stats_ddl_cnt\" WHERE $timeFilter AND \"hostname\" =~ /$backend_nodes/ GROUP BY time($__interval), \"hostname\", \"role\" fill(null)"
    }
   ]
  },
  {
   "title": "Other statement counts",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 14, "y": 23 },
   "targets": [
    {
     "query": "SELECT non_negative_derivative(mean(\"counter\"),1s) FROM \"pgpool2_pool_backend_stats_other_cnt\" WHERE $timeFilter AND \"hostname\" =~ /$backend_nodes/ GROUP BY time($__interval), \"hostname\", \"role\" fill(null)"
    }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "Number of health check count in total",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 30 },
   "targets": [
    {
     "query": "SELECT mean(\"gauge\") FROM \"pgpool2_pool_health_check_stats_total_count\" WHERE $timeFilter AND \"hostname\" =~ /$backend_nodes/ GROUP BY time($__interval), \"hostname\" fill(null)"
    }
   ]
  },
  {
   "title": "Number of Successful Health Check ",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 30 },
   "targets": [
    {
     "query": "SELECT mean(\"gauge\") FROM \"pgpool2_pool_health_check_stats_success_count\" WHERE $timeFilter AND \"hostname\" =~ /$backend_nodes/ GROUP BY time($__interval), \"hostname\" fill(null)"
    }
   ]
  },
  {
   "title": "Number of failed health check",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 30 },
   "targets": [
    {
     "query": "SELECT mean(\"gauge\") FROM \"pgpool2_pool_health_check_stats_fail_count\" WHERE $timeFilter AND \"hostname\" =~ /$backend_nodes/ GROUP BY time($__interval), \"hostname\" fill(null)"
    }
   ]
  },
  {
   "title": "Number of skipped health check",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 30 },
   "targets": [
    {
     "query": "SELECT mean(\"gauge\") FROM \"pgpool2_pool_health_check_stats_skip_count\" WHERE $timeFilter AND \"hostname\" =~ /$backend_nodes/ GROUP BY time($__interval), \"hostname\" fill(null)"
    }
   ]
  },
  {
   "title": "Number of retried health check",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 30 },
   "targets": [
    {
     "query": "SELECT mean(\"gauge\") FROM \"pgpool2_pool_health_check_stats_retry_count\" WHERE $timeFilter AND \"hostname\" =~ /$backend_nodes/ GROUP BY time($__interval), \"hostname\" fill(null)"
    }
   ]
  },
  {
   "title": "Number of maximum retried health check",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "query": "SELECT mean(\"gauge\") FROM \"pgpool2_pool_health_check_stats_max_retry_count\" WHERE $timeFilter AND \"hostname\" =~ /$backend_nodes/ GROUP BY time($__interval), \"hostname\" fill(null)"
    }
   ]
  },
  {
   "title": "Number of average retried health check",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "query": "SELECT mean(\"gauge\") FROM \"pgpool2_pool_health_check_stats_average_retry_count\" WHERE $timeFilter AND \"hostname\" =~ /$backend_nodes/ GROUP BY time($__interval), \"hostname\" fill(null)"
    }
   ]
  },
  {
   "title": "Average health check duration",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "query": "SELECT mean(\"gauge\") FROM \"pgpool2_pool_health_check_stats_average_duration\" WHERE $timeFilter AND \"hostname\" =~ /$backend_nodes/ GROUP BY time($__interval), \"hostname\" fill(null)"
    }
   ]
  },
  {
   "title": "Minimum health check duration",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "query": "SELECT mean(\"gauge\") FROM \"pgpool2_pool_health_check_stats_min_duration\" WHERE $timeFilter AND \"hostname\" =~ /$backend_nodes/ GROUP BY time($__interval), \"hostname\" fill(null)"
    }
   ]
  },
  {
   "title": "Maximum health check duration",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "query": "SELECT mean(\"gauge\") FROM \"pgpool2_pool_health_check_stats_max_duration\" WHERE $timeFilter AND \"hostname\" =~ /$backend_nodes/ GROUP BY time($__interval), \"hostname\" fill(null)"
    }
   ]
  },
  { "title": "Query Cache", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "Query Cache Hit Ratio",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT last(\"gauge\") FROM \"pgpool2_pool_cache_cache_hit_ratio\" WHERE $timeFilter"
    }
   ]
  }
 ]
}