apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.container.name }}-{{ .Values.environment }}
  labels:
    app: {{ .Values.container.name }}-{{ .Values.environment }} # deployment labels
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.container.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.container.name }} # pod labels
        environment: {{ .Values.environment }}
    spec:
      containers:
        - name: {{ .Values.container.name }}
          image: {{ .Values.container.image }}:{{ .Values.container.tag }}
          imagePullPolicy: Always
          ports:
            - containerPort: {{ .Values.container.port }}
          env:
            - name: SERVICE_ENV
              value: {{ .Values.environment | quote }}
            - name: SERVICE_NAME
              value: {{ .Values.serviceName | quote }}
            - name: SERVICE_PORT
              value: {{ .Values.servicePort | quote }}

            - name: LOG_LEVEL
              value: {{ .Values.logLevel | quote }}
            - name: LOG_PATH
              value: {{ .Values.logPath | quote }}

            - name: REDIS_ADDRS
              value: {{ .Values.redisAddrs | quote }}
            - name: REDIS_PASSWORD
              value: {{ .Values.redisPassword | quote }}
            - name: REDIS_CHANNEL
              value: {{ .Values.redisChannel | quote }}
            - name: REDIS_POOL_SIZE
              value: {{ .Values.redisPoolSize | quote }}

            - name: KAFKA_BROKERS
              value: {{ .Values.kafkaBrokers | quote }}
            - name: KAFKA_GROUP_ID
              value: {{ .Values.kafkaGroupId | quote }}
            - name: KAFKA_POOL_SIZE
              value: {{ .Values.kafkaPoolSize | quote }}
            - name: KAFKA_SIGNUP_USER_TOPIC
              value: {{ .Values.kafkaSignupUserTopic | quote }}

            - name: STATSD_ADDR
              value: {{ .Values.statsdAddr | quote }}
            - name: STATSD_PREFIX
              value: {{ .Values.statsdPrefix | quote }}
            - name: STATSD_FLUSH_PERIOD
              value: {{ .Values.statsdFlushPeriod | quote }}

            - name: POSTGRES_HOST
              value: {{ .Values.postgresHost | quote }}
            - name: POSTGRES_PORT
              value: {{ .Values.postgresPort | quote }}
            - name: POSTGRES_USERNAME
              value: {{ .Values.postgresUsername | quote }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.postgresPassword | quote }}
            - name: POSTGRES_DBNAME
              value: {{ .Values.postgresDbName | quote }}
