{{- define "imagePullSecret" }}
{{- printf "{\"auths\":{\"%s\":{\"auth\":\"%s\"}}}" .Values.registry (printf "%s:%s" .Values.registryUsername .Values.registryPassword | b64enc) | b64enc }}
{{- end }}

apiVersion: v1
kind: Secret
metadata:
  name: docker-registry-secret
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}

---
apiVersion: v1
kind: Secret
metadata:
  name: be-private-keys
type: Opaque
data:
  jwt_key.perm: {{ .Values.jwtKeyPerm | b64enc }}
  another_jwt_key.perm: {{ .Values.anotherJwtKeyPerm | b64enc }}


---
apiVersion: v1
kind: Secret
metadata:
  name: changeme-tls
type: kubernetes.io/tls
data:
  tls.key: {{ .Values.domainTlsKey | b64enc }}
  tls.crt: {{ .Values.domainTlsCert | b64enc }}
