Vagrant.configure("2") do |config|
    # Define VM configurations
    vms = [
      { gui_display_name: "es_01", name: "es_1", hostname: "es-01", ip: "192.168.56.151" },
      { gui_display_name: "es_02", name: "es_2", hostname: "es-02", ip: "192.168.56.152" },
      { gui_display_name: "es_03", name: "es_3", hostname: "es-03", ip: "192.168.56.153" }
    ]
  
    vms.each do |vm|
      config.vm.define vm[:name] do |vm_config|
        vm_config.vm.box = "ubuntu/jammy64" # Specify the box you want to use
        # vm_config.vm.box = "rockylinux/9" # Specify the box you want to use

        # Fixed IP addresses for private network
        vm_config.vm.network "private_network", ip: vm[:ip]
  
        vm_config.vm.provider "virtualbox" do |vb|
          vb.name = vm[:gui_display_name]
          vb.memory = "4096" # 4GB
          vb.cpus = 4
        end
  
        # Build the hosts string
        # hosts_entries = vms.map { |other_vm| "#{other_vm[:ip]} #{other_vm[:hostname]}" unless other_vm[:hostname] == vm[:hostname] }.compact.join("\n")
        hosts_entries = vms.map { |other_vm| "#{other_vm[:ip]} #{other_vm[:hostname]}" }.join("\n")
  
        # Provision the VM with the hosts entries
        vm_config.vm.provision "shell", inline: <<-SHELL
          # Set hostname
          hostnamectl set-hostname #{vm[:hostname]}
          echo "127.0.0.1 #{vm[:hostname]}" >> /etc/hosts
          echo "#{hosts_entries}" >> /etc/hosts

          # Add SSH public key to authorized keys
          # Remember to generate your own SSH key pair 
          echo "#{File.read(File.expand_path('~/.ssh/id_ed25519.pub'))}" >> /home/vagrant/.ssh/authorized_keys

          # Change permission of authorized key
          chmod 600 /home/vagrant/.ssh/authorized_keys
          chown vagrant:vagrant /home/vagrant/.ssh/authorized_keys
        SHELL
      end
    end
  end
  
