environment: dev

serviceName: boilerplate
servicePort: 8001
logLevel: INFO
logPath: logs/app.log

redisAddrs: 192.168.101.14:6379
redisPassword:
redisChannel:
redisPoolSize: 20

kafkaBrokers: kafka:9092
kafkaGroupId: boilerplate
kafkaClientUser: user
kafkaPoolSize: 30
kafkaSignupUserTopic: register

postgresHost: postgresql-ha-pgpool
postgresPort: 5432
postgresUsername: postgres
postgresDbName: golang_boilerplate

statsdAddr: 192.168.101.14:8125
statsdPrefix: boilerplate_prefix
statsdFlushPeriod: 100

container:
  name: boilerplate-be
  port: 8001
  image: docker.io/duyle95/golang-boilerplate-be
  tag: v1
replicas: 3

# imageCredentials:
registry: docker.io
registryUsername: duyle95
