services:
  jenkins:
    image: myjenkins:2.516.1-lts
    build: 
      context: .
    container_name: jenkins
    restart: always
    user: root                
    ports:
      - "8080:8080"      # Jenkins web UI
      - "50000:50000"    # Jenkins agent port
    environment:
      JENKINS_OPTS: "--prefix=/jenkins"           # optional: run under /jenkins path
    volumes:
      - jenkins_home:/var/jenkins_home    
      # - /var/run/docker.sock:/var/run/docker.sock  # allow Jenkins (and its Docker plugins) to use host Docker
      # - /usr/bin/docker:/usr/bin/docker            # mount docker CLI for in-container builds

volumes:
  jenkins_home:
    driver: local
